src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view,
       # payment_success,
       # payment_failure,
        #list_payments,
        payment
        )

urlpatterns = [

    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
    #url(r'^list/', list_payments, name="list"),
    url(r'^payment/', payment, name="payment"),

	#url(r'^payment/success$', payment_success, name="payment_success"),
	#url(r'^payment/failure$',payment_failure, name="payment_failure"),
]

src/technofresh/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import LogoutView
from .views import home_page,about
from banner.views import photo_list
from offersimages.views import offers_list
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from analytics.views import SalesView,SalesAjaxView
from accounts.views import LoginView, RegisterView,GuestRegisterView
from products.views import product_detail_view, ProductFeaturedDetailView,ProductFeaturedListView
from carts.views import cart_detail_api_view
from billing.views import payment,success,failure
from django.views.generic import RedirectView
#from carts.views import 
urlpatterns = [

    url(r'^$',home_page,name='home'),
    url(r'^about/$',about,name='about'),
    url(r'^banners/$',photo_list,name='photo_list'),
    url(r'^offers/$',offers_list,name='offers_list'),
    #url(r'^(?P<slug>[-\w]+)$',AlbumDetail.as_view(),name='album'),
    url(r'^accounts/$', RedirectView.as_view(url='/login')),
    url(r'^account/', include("accounts.urls",namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^register/guest/$',GuestRegisterView.as_view(),name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    url(r'^api/cart/$',cart_detail_api_view,name='api-cart'),
    #url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/', include("carts.urls",namespace='cart')),
    url(r'^billing/payment/$',payment, name="payment"),
    url(r'^payment/success$', success, name="payment_success"),
    url(r'^payment/failure$', failure, name="payment_failure"),
    url(r'^orders/', include("orders.urls",namespace='orders')),
    url(r'^products/', include("products.urls",namespace='products')),
    url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    url(r'^search/', include("search.urls",namespace='search')),
    url(r'^categories/', include('products.urls_categories')),
    #url(r'^$',HomepageView.as_view(),name ='HomepageView')
    url(r'^analytics/sales/$', SalesView.as_view(),name='sales-analytics'),
    url(r'^analytics/sales/data/$',SalesAjaxView.as_view(),name='sales-analytics-data'),
    url(r'^featured/$', ProductFeaturedListView.as_view(), name='products'),
    url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view(), name='products'),
    url(r'^admin/', admin.site.urls),
    #url(r'^paytm/', include('paytm.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed,post_delete
from products.models import Product,Variation

User = settings.AUTH_USER_MODEL

# Create your models here.


class CartItem(models.Model):
    cart = models.ForeignKey("Cart")
    item = models.ForeignKey(Variation)
    quantity = models.PositiveIntegerField(default=1)
    line_item_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.item.title

    def remove(self):
        return self.item.remove_from_cart()


def cart_item_pre_save_receiver(sender, instance, *args, **kwargs):
    qty = instance.quantity
    if qty >= 1:
        price = instance.item.get_price()
        line_item_total = Decimal(qty) * Decimal(price)
        instance.line_item_total = line_item_total

pre_save.connect(cart_item_pre_save_receiver, sender=CartItem)



def cart_item_post_save_receiver(sender, instance, *args, **kwargs):
    instance.cart.update_subtotal()

post_save.connect(cart_item_post_save_receiver, sender=CartItem)

post_delete.connect(cart_item_post_save_receiver, sender=CartItem)

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)
class Cart(models.Model):
    quantity    = models.PositiveIntegerField(default=1)
    items = models.ManyToManyField(Variation, through=CartItem)
    user        = models.ForeignKey(User, null=True, blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    objects		= CartManager()
    
    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)




def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0 and instance.subtotal :
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

src/carts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from carts.apitest import apitest
from django.urls import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from orders.models import Order
from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin
from addresses.models import Address
from billing.models import BillingProfile
from products.models import Product
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from accounts.forms import LoginForm,GuestForm
from .models import Cart
from billing.views import payment
from instamojo_wrapper import Instamojo
from django.contrib.auth.decorators import login_required
# Create your views here.


api = Instamojo(api_key=apitest.API_KEY, auth_token=apitest.AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/')
def cart_detail_api_view(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	products = [{
				"id":x.id,
				"url":x.get_absolute_url(),
				"name":x.title,
				"price":x.price,
				}
				 for x in cart_obj.products.all()]
	cart_data = {"products":products,"subtotal":cart_obj.subtotal,"total":cart_obj.total}
	return JsonResponse(cart_data)
def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    context = {
    	'cart' : cart_obj
    }
    return render(request, "carts/home.html",context)


def cart_update(request):
	product_id = request.POST.get('product_id')

	if product_id is not None:
		try :
			product_obj = Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			print("Product Is Gone")
			return redirect("cart:home")
		
		cart_obj,new_obj= Cart.objects.new_or_get(request)
		if product_obj in cart_obj.products.all():
			cart_obj.products.remove(product_obj)
			added = False
		else:
			cart_obj.products.add(product_obj)
			added = True
		request.session['cart_items'] = cart_obj.products.count()
		if request.is_ajax():
			print("Ajax request")
			json_data = {
				"added" : added,
				"removed" : not added,
				"cartItemCount":cart_obj.products.count()
			}
			return JsonResponse(json_data,status=200)
			#return JsonResponse({"message" : "Error 400"},status_code=400)
	return redirect("cart:home")
@login_required
def checkout_home(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.products.count() == 0:
		return redirect("cart:home")


	login_form =LoginForm(request=request)
	guest_form	= GuestForm(request=request)
	address_form = AddressForm()
	billing_address_id = request.session.get("billing_address_id",None)
	shipping_address_id = request.session.get("shipping_address_id",None)

	
	billing_profile ,billing_profile_created = BillingProfile.objects.new_or_get(request)
	address_qs = None
	if billing_profile is not None :
		if request.user.is_authenticated() :
			address_qs 			= Address.objects.filter(billing_profile=billing_profile)
		order_obj, order_obj_created = Order.objects.new_or_get(billing_profile,cart_obj)
		if shipping_address_id:
			order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
			del request.session["shipping_address_id"]
		if billing_address_id :
			order_obj.billing_address = Address.objects.get(id=billing_address_id)
			del request.session["billing_address_id"]
		if billing_address_id or shipping_address_id :
			order_obj.save()

	if request.method == "POST" :
		#"check that order is done"
		is_done = order_obj.check_done()
		if is_done:
			order_obj.mark_paid()
			request.session['cart_items'] = 0
			del request.session['cart_id']
		return redirect("cart:success")
	
	context = {
		"object": order_obj,
		"billing_profile" :billing_profile,
		"login_form": login_form,
		"guest_form" : guest_form,
		"address_form": address_form,
 		"address_qs":address_qs
		
	}
	return render(request,"carts/checkout.html", context )


def checkout_done_view(request):
	return render(request,"carts/checkout-done.html",{})


def list_payments(request):
    # Create a new Payment Request
    response = api.payment_requests_list()

    # Loop over all of the payment requests
    h = "<div><table><tr><th>ID</th><th>amount</th><th>Purpose</th><th>status</th></tr>"
    for payment_request in response['payment_requests']:
        h += "<tr>"
        h += "<td>" + payment_request['id'] + "</td>"
        h += "<td>" + payment_request['amount'] + "</td>"
        h += "<td>" + payment_request['purpose'] + "</td>"
        h += "<td>" + payment_request['status'] + "</td>"
        h += "</tr>"

    h += "</table></div>"

    return HttpResponse(h)

src/carts/templates/carts/checkout-done.html
{% extends "base.html" %}

{% block content %}

<div class='col-6 mx-auto py-5 text-center'>
	<h1 class='display-1'>Thank you for your order!!!</h1>
</div>

{% endblock %}

src/carts/templates/carts/checkout.html
{% extends 'base.html' %}
{% block content %}


{% if not billing_profile %}
	<div class="row text-center">
		<div class='col-12 col-md-6'>
			<p class='lead'>Login</p>
			{% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
		</div>
		<div class='col-12  col-md-6'>
			Continue as Guest

			{% url "guest_register" as guest_regsiter_url %}
			{% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_regsiter_url %}
		</div>
	</div>

{% else %}

		{% if not object.shipping_address  %}
		<div class ='row'>
			<div class="col-12">
				<p class='lead'>Shipping Address</p>
				<hr/>
			</div>
			<div class="container">
				<div class='col-12 md-16 sm-6 lg-12'>
					
				

					{% url "checkout_address_create" as checkout_address_create %}
					{% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
				</div>
			</div>
			
				
			
		</div>
		{% elif not object.billing_address %}
		 <div class ='row'>
			<div class='col-12'>
				<p class='lead'>Billing Address</p>
				<hr/>
				{% url "checkout_address_create" as checkout_address_create %}
				{% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
				>
			</div>
				

		</div>
		{% else %}
		<div class="card" style="width: 135rem;">
			<div class="card-body">
				<h1 class="card-title ml-7">Finalize CheckOut</h1>
				<h6 class="card-subtitle mb-2">Cart Items : {% for product in object.cart.products.all %}{{product}}{% if not forloop.last %}, {% endif %}{% endfor %} </h6>
				<p>Shipping Address : {{ object.shipping_address.get_address|title }}</p>
				<p>Billing Address : {{ object.billing_address.get_address|title }}</p>

				<p>Cart Total : {{ object.cart.total }} </p>
				{% if object.cart.total < 200 %}
					<p> Shipping Total: {{ object.shipping_total }}</p>
				{% else %}
					<p> Shipping Total: {{ 0 }}</p>
				{% endif %}
				<p>Order Total: {{ object.total }}</p>	
			</div>
		</div>
			
	
	<div class="container mt-4">
		<h1 class="text-center mt-6">Choose Your Payment Options</h1>
		<div class="card-deck">
			<div class="card" style="width: 18rem;">
				<div class="card-body">
			    <p class="card-text display1" style="margin: 40px; font-size: 1.5em;">At your click, we deliver freshness.</p>
			    <form class='form' method="POST" action="">{% csrf_token %}
					<button type="submit" class="btn btn-lg btn-success" style="margin-top: 10px; margin-left: 80px;">Cash on delivery</button>
			  	</div>
			</div>
			<div class="card" style="width: 18rem;">
			  <div class="card-body">
			     <p class="card-text display1" style="margin: 40px; font-size: 1.5em;">At your click, we deliver freshness.</p>
			    <div class="checkout">
			    	<a href="https://test.instamojo.com/@ajaymundhe21/" rel="im-checkout" data-behaviour="remote" data-style="flat" data-text="Checkout With Instamojo"></a>
					<script src="https://js.instamojo.com/v1/button.js"></script>
				</div>
			  </div>
			</div>
			<div class="card" style="width: 18rem;">
			  <div class="card-body">
			     <p class="card-text display1" style="margin: 40px; font-size: 1.5em;">At your click, we deliver freshness.</p>
			   	 <button type="button" class="btn btn-lg btn-success" disabled style="margin-top: 10px; margin-left: 80px;">Payumoney</button>
			  </div>
			</div>
		</div>
	</div>
		{% endif %}
{% endif %}


{% endblock %}

src/carts/templates/carts/checkout1.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
 <script type="text/javascript">
    var hash = "{{ hashh }}";
    function submitPayuForm() {
      if(hash =='') {
        return;
      }
      var payuForm = document.forms.payuForm;
      payuForm.submit();
    }
  </script>

{% if not billing_profile %}
	<div class="row text-center">
		<div class='col-12 col-md-6'>
			<p class='lead'>Login</p>
			{% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
		</div>
		<div class='col-12  col-md-6'>
			Continue as Guest

			{% url "guest_register" as guest_regsiter_url %}
			{% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_regsiter_url %}
		</div>
	</div>

{% else %}

		{% if not object.shipping_address  %}
		<div class ='row'>
			<div class="col-12">
				<p class='lead'>Shipping Address</p>
				<hr/>
			</div>
			<div class='col-6'>
				
			

				{% url "checkout_address_create" as checkout_address_create %}
				{% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
			</div>
			
				
			
		</div>
		{% elif not object.billing_address %}
		 <div class ='row'>
			<div class='col-12'>
				<p class='lead'>Billing Address</p>
				<hr/>
				{% url "checkout_address_create" as checkout_address_create %}
				{% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
				>
			</div>

		</div>
		{% else %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 sm-6">
                   <form action="https://test.payu.in/_payment"  name="payuForm" method="post">    
                    {% csrf_token %}        
                    <input type="hidden" name="key" value="{{ key }}" />            
                    <input type="hidden" name="hash" value="{{ hash_ }}"/>            
                    <input type="hidden" name="txnid" value="{{ txnid }}" />
                    <input type="hidden" name="amount" value="{{ amount }}" />
                    <input type="hidden" name="email" value="{{ User }}" />
                    <input type="hidden" name="firstname" value="{{ Name }}" />
                    <input type="hidden" name="phone" value="{{ Mobile }}" />
                    <input type="hidden" name="productinfo" value="{{product}}"/>
                    <input type="hidden" name="hash_string" value="{{ hash_ }}" />
                    <input type="hidden" name="surl" value="{{surl}}"/>
                    <input type="hidden" name="furl" value="{{ furl }}" />
                    <input type="hidden" name="service_provider" value="{{ service_provider }}" />
                    
                    <div class="form-inline">
                        <div class="col-md-12 col-sm-12">
                            Amount : {{amount}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12">
                            Products :{{product}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12">
                            Name : {{Name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12">
                            Email : {{User}}
                        </div>
                    </div>            
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12">
                            Mobile : {{billing_profile.mobile_no}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12">
                            Transaction ID : {{txnid}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12" style="padding-bottom:20px;padding-top:20px;">
                            After clicking 'Pay Now' button, you will be redirected to PayUMoney Secure Gateway.
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-md-6 col-sm-12">
                            <input type="submit" class="btn btn-success btn-lg" value="Pay Now">
                        </div>
                    </div>
                    </form>
                    
                    <p>Choose Your Payment At Your Doorstep</p>
                    <h2 class='text-center ' >OR</h2>
                    <form class='form col-md-6' method="POST" action="">{% csrf_token %}
                        <input type="submit" class="btn btn-success btn-md" value="Cash On Deleivery"></input>
                    </form>
                    <a href="https://test.instamojo.com/@ajaymundhe21/" rel="im-checkout" data-behaviour="remote" data-style="light" data-text="Checkout With Instamojo"></a>
            <script src="https://js.instamojo.com/v1/button.js"></script>
                </div>
            </div>
        </div>
        {% endif %}
{% endif %}



{% endblock %}

    

src/carts/templates/carts/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>                
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="#" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}

src/carts/templates/carts/home.html
{% extends 'base.html' %}
{% block content %}
<h1> Cart</h1>
{% if cart.products.exists %}
<table class="table cart-table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
      
    </tr>
  </thead>
  <tbody class='cart-body'>
   
      {% for product in cart.products.all %}
        <tr class='cart-product'>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ product.title }}
		          {% include 'carts/snippets/remove-product.html' with product_id=product.id %}

            </td>
            <td>₹{{ product.price }}</td>
        </tr>
      {% endfor %}
    
    <tr>
      <td colspan="2"></td>
      
      <td><b>Subtotal:</b>  ₹<span class='cart-subtotal'>{{ cart.subtotal }}</span></td>
    </tr>
    <tr>
      <td colspan="2"></td>
      
      <td><b>Total:</b> <span class='cart-total'> ₹{{ cart.total }}</span></td>
      <tr>
      <td colspan="2"></td>
      
      <td><a class ='btn btn-lg btn-success' href='{% url "cart:checkout" %}'>Checkout</a>
     
    </tr>
    </tr>
  </tbody>
</table>
<div class='cart-item-remove-form' style='display:none'>
  {% include 'carts/snippets/remove-product.html' %}

</div>
{% else %}
<p class='lead'>Cart is empty</p>
{% endif %}

{% endblock %}

src/carts/templates/carts/view.html
{% extends "base.html" %}

<h1>hello</h1>
<script>

$(".item-qty").change(function(){
	// $(this).next(".btn-update").fadeIn();

	// event.preventDefault();
	// .prev(h1)
	var item = $(this).prev("input[type='hidden']").val();
	var qty = $(this).val()
	var data = {
		item: item,
		qty: qty
	}
	console.log(data);
	$.ajax({
		type: "GET", // "POST"
		url: "{% url 'cart' %}",
		data: data,
		success: function(data) {
			$("#jquery-message").text("Added " + data.item_added + " Deleted " + data.deleted)
			if (data.deleted){
				$("#item-"+item).fadeOut();
				$("#subtotal").text(data.subtotal);
				$("#taxtotal").text(data.tax_total);
				$("#carttotal").text(data.cart_total);
			} else {
				$("#item-line-total-"+item).text(data.line_total);
				$("#subtotal").text(data.subtotal);
				$("#taxtotal").text(data.tax_total);
				$("#carttotal").text(data.cart_total);
			}

			if (data.total_items == 0 ) {
				$(".table").fadeOut()
				var template = "{% include 'carts/empty_cart.html' %}";
				$(".main-content").html(template);

			}

			var message = ""
			if (data.item_added) {
				message = "New item added"
			} else if (data.deleted){
				message = "Item removed"
			} else {
				message = "Item updated"
			}
			showFlashMessage(message);
			updateCartItemCount()
			}, 
		error: function(response, error) {
			// console.log(response)
			// console.log(error)
			$("#add-form").submit()
		}
	})





});


</script>

{% block content %}


<div class='row main-content'>

{% if object.cartitem_set.count < 1 %}

{% include "carts/empty_cart.html" %}
{% else %}

<div class='col-sm-8 col-sm-offset-2'>

<h1>Your cart</h1>
<table class='table'> 


{% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}

<tr id='item-{{ item.item.id }}'>

<td>{{ item.item.get_title }}</td>


<td><form action="." method="GET" ><input type='hidden' name='item' value='{{ item.item.id }}' /><input type='number' class='item-qty' name='qty' value='{{ product.quantity }}' /><input type='submit' class='btn-update btn btn-link' value='Update item' style='display:none;'/></form></td>
<td id='item-line-total-{{ item.item.id }}'>{{ item.line_item_total }}</td>
<td class='text-right' ><a href='{{ item.remove }}'>X</a>



</td>


</tr>

{% endfor %}


<tr>
	<td  colspan='4' class='text-right'>Subtotal: <span id='subtotal'>{{ object.subtotal }}</span></td>
</tr>

<tr>
	<td colspan='4' class='text-right'>Tax (Estimated): <span id='taxtotal'>{{ object.tax_total }}</span></td>
</tr>

<tr>
	<td colspan='4' class='text-right'>Total: <span id='carttotal'>{{ object.total }}</span></td>
</tr>


<tr>
	<td colspan='4' class='text-right'><a class='btn btn-warning' href="{% url 'cart:checkout' %}">Checkout </a></td>
</tr>

</table>


</div>
{% endif %}

</div>
{% endblock %}