src/accounts/passwords/urls.py
# accounts.passwords.urls.py 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
        url(r'^password/change/$', 
                auth_views.PasswordChangeView.as_view(), 
                name='password_change'),
        url(r'^password/change/done/$',
                auth_views.PasswordChangeDoneView.as_view(), 
                name='password_change_done'),
        url(r'^password/reset/$', 
                auth_views.PasswordResetView.as_view(), 
                name='password_reset'),
        url(r'^password/reset/done/$', 
                auth_views.PasswordResetDoneView.as_view(), 
                name='password_reset_done'),
        url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
                auth_views.PasswordResetConfirmView.as_view(), 
                name='password_reset_confirm'),
        url(r'^password/reset/complete/$', 
                auth_views.PasswordResetCompleteView.as_view(), 
                name='password_reset_complete'),
]

src/accounts/urls.py
from django.conf.urls import url

from .views import (
        AccountHomeView,
        AccountEmailActivateView,
        UserDetailUpdateView,

        )
from products.views import UserProductHistoryListView

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'^history/products$',UserProductHistoryListView.as_view(),name='user-product-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', 
            AccountEmailActivateView.as_view(), 
            name='resend-activation'),
]

src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view,
       # payment_success,
       # payment_failure,
        #list_payments,
        payment
        )

urlpatterns = [

    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
    #url(r'^list/', list_payments, name="list"),
    url(r'^payment/', payment, name="payment"),

	#url(r'^payment/success$', payment_success, name="payment_success"),
	#url(r'^payment/failure$',payment_failure, name="payment_failure"),
]

src/technofresh/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import LogoutView
from .views import home_page,about
from banner.views import photo_list
from offersimages.views import offers_list
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from analytics.views import SalesView,SalesAjaxView
from accounts.views import LoginView, RegisterView,GuestRegisterView
from products.views import product_detail_view, ProductFeaturedDetailView,ProductFeaturedListView
from carts.views import cart_detail_api_view
from billing.views import payment,success,failure
from django.views.generic import RedirectView
#from carts.views import 
urlpatterns = [

    url(r'^$',home_page,name='home'),
    url(r'^about/$',about,name='about'),
    url(r'^banners/$',photo_list,name='photo_list'),
    url(r'^offers/$',offers_list,name='offers_list'),
    #url(r'^(?P<slug>[-\w]+)$',AlbumDetail.as_view(),name='album'),
    url(r'^accounts/$', RedirectView.as_view(url='/login')),
    url(r'^account/', include("accounts.urls",namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^register/guest/$',GuestRegisterView.as_view(),name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    url(r'^api/cart/$',cart_detail_api_view,name='api-cart'),
    #url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/', include("carts.urls",namespace='cart')),
    url(r'^billing/payment/$',payment, name="payment"),
    url(r'^payment/success$', success, name="payment_success"),
    url(r'^payment/failure$', failure, name="payment_failure"),
    url(r'^orders/', include("orders.urls",namespace='orders')),
    url(r'^products/', include("products.urls",namespace='products')),
    url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    url(r'^search/', include("search.urls",namespace='search')),
    url(r'^categories/', include('products.urls_categories')),
    #url(r'^$',HomepageView.as_view(),name ='HomepageView')
    url(r'^analytics/sales/$', SalesView.as_view(),name='sales-analytics'),
    url(r'^analytics/sales/data/$',SalesAjaxView.as_view(),name='sales-analytics-data'),
    url(r'^featured/$', ProductFeaturedListView.as_view(), name='products'),
    url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view(), name='products'),
    url(r'^admin/', admin.site.urls),
    #url(r'^paytm/', include('paytm.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/forms.py
from django.contrib.auth import authenticate,login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.safestring import mark_safe
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .models import GuestEmail,EmailActivation
from django import forms

User = get_user_model()
class ReactivateEmailForm(forms.Form):
    email       = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = EmailActivation.objects.email_exists(email) 
        if not qs.exists():
            register_link = reverse("register")
            msg = """This email does not exists, would you like to <a href="{link}">register</a>?
            """.format(link=register_link)
            raise forms.ValidationError(mark_safe(msg))
        return email



class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name','email')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ['full_name']

        
class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name','email', 'password', 'is_active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)
    def clean(self):
        request = self.request
        data = self.cleaned_data
        email  = data.get("email")
        password  = data.get("password")
        qs = User.objects.filter(email=email)
        if qs.exists():
            # user email is registered, check active/
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                ## not active, check email activation
                link = reverse("account:resend-activation")
                reconfirm_msg = """Go to <a href='{resend_link}'>
                resend confirmation email</a>.
                """.format(resend_link = link)
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account or " + reconfirm_msg.lower()
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))
                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError("This user is inactive.")
        user = authenticate(request, username=email, password=password)
        if user is None:
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        self.user = user
        return data

class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name','email')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False # send comfirm email actication
        #obj , is_created = EmailActivation.objects.create(user=user)
        #obj.send_activation
        if commit:
            user.save()
        return user


class GuestForm(forms.ModelForm):
    #email    = forms.EmailField()
    class Meta:
        model = GuestEmail
        fields = [
            'email',
            'full_name',
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(GuestForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        # Save the provided password in hashed format
        obj = super(GuestForm, self).save(commit=False)
        if commit:
            obj.save()
            request = self.request
            request.session['guest_email_id'] = obj.id
            request.session['guest_full_name'] = obj.id
        return obj

src/accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import CreateView,FormView,DetailView,View, UpdateView
from django.views.generic.edit import FormMixin
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe
from django.utils.http import is_safe_url
from .forms import LoginForm,RegisterForm,GuestForm,ReactivateEmailForm,UserDetailChangeForm
from.models import GuestEmail,EmailActivation
from .signals import user_logged_in
from django.core.urlresolvers import reverse
from technofresh.mixins import NextUrlMixin,RequestFormAttachMixin

class AccountHomeView(LoginRequiredMixin,DetailView):
  template_name = "accounts/home.html"
  def get_object(self):
    return self.request.user


class AccountEmailActivateView(FormMixin,View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login") 
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user 
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)


class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(CreateView):
    form_class    = RegisterForm
    template_name = 'accounts/register.html'
    success_url   =  '/login/'

class GuestRegisterView(NextUrlMixin,RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)

class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")

src/accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
  <button type='submit' class='btn btn-default my-3'>Save</button>
  <a href='{% url "password_change" %}'>Change Password</a>
</form>
</div>
{% endblock %}

src/accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
<style type="text/css" media="screen">
  .list-group-item a {
    color: black;
  }
</style>
<div class='row'>
<div class='col-12'>
<h1>Account</h1>
<hr/>
</div>
<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Support</h4>
            <div class='list-group'>
                <a class='list-group-item' href='#'>About</a>
                <a class='list-group-item' href='#'>Contact</a>
            </div>
      </div>
    </div>
</div>



<div class='col-12 col-md-3 my-3' id='billing'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Billing</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "orders:list" %}'>Orders</a>
                <a class='list-group-item' href='#'>Payment Methods</a>
                <a class='list-group-item' href='#'>Addresses</a>
                
                
            </div>
      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Account Details</h4> 
            <div class='list-group'>
                <a class='list-group-item' href="{% url 'account:user-update' %}">Update Details</a>
                <a class='list-group-item' href='{% url "password_change" %}'>Change Password</a>
                <a class='list-group-item' href='#'>Library</a>
                
            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Preferences</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='#'>Email Marketing</a>
                
            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History</h4> 
              <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-product-history" %}'>Products Viewd</a>
            </div>
      </div>
    </div>
</div>


</div>


{% endblock %}

src/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}
	<div class="container">
		<div class='row'>
		<div class='col-sm-6 col-sm-offset-3'>
		<h1>Login</h1>
		<form method="post" action=".">
			  {% csrf_token %}
			  {{ form|crispy }}

		  <input class='btn btn-block btn-primary' type="submit" value="{% trans 'Submit' %}" />
		  <input type="hidden" name="next" value="{{ next }}" />
		</form>
		</div>

		</div>
		<hr/>
		<div class='row'>
		<div class='col-sm-6 col-sm-offset-3 text-align-center'>
		<p>{% trans "Forgot password" %}? <a href="{% url 'password_change' %}">{% trans "Reset it" %}</a>!</p>
		<p>{% trans "Not member" %}? <a href="{% url 'register' %}">{% trans "Register" %}</a>!</p>
		</div>
		</div>
	</div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
	
	<div class="container">
		<h1>Register</h1>
		    <form method='POST'> {% csrf_token %}
		       {{ form|crispy }}
		      
		      <button type='submit' class='btn btn-default'>Submit</button>
		    </form>
	</div>

{% endblock %}