src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view,
       # payment_success,
       # payment_failure,
        #list_payments,
        payment
        )

urlpatterns = [

    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
    #url(r'^list/', list_payments, name="list"),
    url(r'^payment/', payment, name="payment"),

	#url(r'^payment/success$', payment_success, name="payment_success"),
	#url(r'^payment/failure$',payment_failure, name="payment_failure"),
]

src/products/urls.py
from django.conf.urls import include, url



from .views import ProductDetailView, ProductDetailSlugView, ProductListView,VariationListView,ProductFeaturedListView, ProductFeaturedDetailView, product_detail_view

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$',ProductDetailView.as_view()),
    url(r'^(?P<slug>[\w-]+)/$',ProductDetailSlugView.as_view(), name='detail'),
    url(r'^$', ProductFeaturedListView.as_view(), name='featured-products'),
    
    url(r'^(?P<pk>\d+)/$',ProductDetailView.as_view()),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='product_inventory'),
    #url(r'^(?P<id>\d+)', product_detail_view, name='product-fbv'),


]

src/technofresh/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import LogoutView
from .views import home_page,about
from banner.views import photo_list
from offersimages.views import offers_list
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from analytics.views import SalesView,SalesAjaxView
from accounts.views import LoginView, RegisterView,GuestRegisterView
from products.views import product_detail_view, ProductFeaturedDetailView,ProductFeaturedListView
from carts.views import cart_detail_api_view
from billing.views import payment,success,failure
from django.views.generic import RedirectView
#from carts.views import 
urlpatterns = [

    url(r'^$',home_page,name='home'),
    url(r'^about/$',about,name='about'),
    url(r'^banners/$',photo_list,name='photo_list'),
    url(r'^offers/$',offers_list,name='offers_list'),
    #url(r'^(?P<slug>[-\w]+)$',AlbumDetail.as_view(),name='album'),
    url(r'^accounts/$', RedirectView.as_view(url='/login')),
    url(r'^account/', include("accounts.urls",namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^register/guest/$',GuestRegisterView.as_view(),name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    url(r'^api/cart/$',cart_detail_api_view,name='api-cart'),
    #url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/', include("carts.urls",namespace='cart')),
    url(r'^billing/payment/$',payment, name="payment"),
    url(r'^payment/success$', success, name="payment_success"),
    url(r'^payment/failure$', failure, name="payment_failure"),
    url(r'^orders/', include("orders.urls",namespace='orders')),
    url(r'^products/', include("products.urls",namespace='products')),
    url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    url(r'^search/', include("search.urls",namespace='search')),
    url(r'^categories/', include('products.urls_categories')),
    #url(r'^$',HomepageView.as_view(),name ='HomepageView')
    url(r'^analytics/sales/$', SalesView.as_view(),name='sales-analytics'),
    url(r'^analytics/sales/data/$',SalesAjaxView.as_view(),name='sales-analytics-data'),
    url(r'^featured/$', ProductFeaturedListView.as_view(), name='products'),
    url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view(), name='products'),
    url(r'^admin/', admin.site.urls),
    #url(r'^paytm/', include('paytm.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/forms.py
from django import forms

from django.forms.models import modelformset_factory


from .models import Variation, Category


CAT_CHOICES = (
	('electronics', 'Electronics'),
	('accessories', 'Accessories'),
)

class ProductFilterForm(forms.Form):
	q = forms.CharField(label='Search', required=False)
	category_id = forms.ModelMultipleChoiceField(
		label='Category',
		queryset=Category.objects.all(), 
		widget=forms.CheckboxSelectMultiple, 
		required=False)
	# category_title = forms.ChoiceField(
	# 	label='Category',
	# 	choices=CAT_CHOICES, 
	# 	widget=forms.CheckboxSelectMultiple, 
	# 	required=False)
	max_price = forms.DecimalField(decimal_places=2, max_digits=12, required=False)
	min_price = forms.DecimalField(decimal_places=2, max_digits=12, required=False)



class VariationInventoryForm(forms.ModelForm):
	class Meta:
		model = Variation
		fields = [
			"price",
			"sale_price",
			"inventory",
			"active",
		]


VariationInventoryFormSet = modelformset_factory(Variation, form=VariationInventoryForm, extra=0)

src/products/views.py
from django.core.exceptions import ImproperlyConfigured
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from carts.models import Cart

from analytics.mixins import ObjectViewedMixin
from django_filters import FilterSet, CharFilter, NumberFilter
# Create your views here.

from .forms import VariationInventoryFormSet, ProductFilterForm
from .mixins import StaffRequiredMixin
from .models import Product, Variation, Category
import random

class ProductFeaturedListView(ListView):
	template_name ='products/product_list.html'

	def get_queryset(self,*args,**kwargs):
		request =self.request
		return Product.objects.featured()
	def get_context_data(self,*args,**kwargs):
		context = super(ProductFeaturedListView,self).get_context_data(*args,**kwargs)

		cart_obj=Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context

class ProductFeaturedDetailView(ObjectViewedMixin,DetailView):
	#queryset = Product.objects.all()
	template_name = "products/featured-detail.html"


	def get_queryset(self,*args,**kwargs):
		request =self.request
		return Product.objects.featured()

	def get_context_data(self,*args,**kwargs):
		context = super(ProductFeaturedDetailView,self).get_context_data(*args,**kwargs)

		cart_obj=Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context

	#def get_object(self,*args,**
class CategoryListView(ListView):
	model = Category
	queryset = Category.objects.all()
	template_name = "products/category_list1.html"




class CategoryDetailView(ObjectViewedMixin,DetailView):
	model = Category

	def get_context_data(self, *args, **kwargs):
		context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
		obj = self.get_object()

		product_set = obj.product_set.all()
		default_products = obj.default_category.all()
		products = ( product_set | default_products ).distinct()
		categories = Category.objects.all()
		context["products"] = products
		context ["categories"] = categories
		return context



class VariationListView(StaffRequiredMixin, ListView):
	model = Variation
	queryset = Variation.objects.all()

	def get_context_data(self, *args, **kwargs):
		context = super(VariationListView, self).get_context_data(*args, **kwargs)
		context["formset"] = VariationInventoryFormSet(queryset=self.get_queryset())
		return context

	def get_queryset(self, *args, **kwargs):
		product_pk = self.kwargs.get("pk")
		if product_pk:
			product = get_object_or_404(Product, pk=product_pk)
			queryset = Variation.objects.filter(product=product)
		return queryset

	def post(self, request, *args, **kwargs):
		formset = VariationInventoryFormSet(request.POST, request.FILES)
		if formset.is_valid():
			formset.save(commit=False)
			for form in formset:
				new_item = form.save(commit=False)
				#if new_item.title:
				product_pk = self.kwargs.get("pk")
				product = get_object_or_404(Product, pk=product_pk)
				new_item.product = product
				new_item.save()
				
			messages.success(request, "Your inventory and pricing has been updated.")
			return redirect("products")
		raise Http404



class ProductFilter(FilterSet):
	title = CharFilter(name='title', lookup_type='icontains', distinct=True)
	category = CharFilter(name='categories__title', lookup_type='icontains', distinct=True)
	category_id = CharFilter(name='categories__id', lookup_type='icontains', distinct=True)
	min_price = NumberFilter(name='variation__price', lookup_type='gte', distinct=True) # (some_price__gte=somequery)
	max_price = NumberFilter(name='variation__price', lookup_type='lte', distinct=True)
	class Meta:
		model = Product
		fields = [
			'min_price',
			'max_price',
			'category',
			'title',
			'description',
		]


def product_list(request):
	qs = Product.objects.all()
	ordering = request.GET.get("ordering")
	if ordering:
		qs = Product.objects.all().order_by(ordering)
	f = ProductFilter(request.GET, queryset=qs)
	return render(request, "products/product_list.html", {"object_list": f })



	filter_class = None
	search_ordering_param = "ordering"

	def get_queryset(self, *args, **kwargs):
		try:
			qs = super(FilterMixin, self).get_queryset(*args, **kwargs)
			return qs
		except:
			raise ImproperlyConfigured("You must have a queryset in order to use the FilterMixin")

	def get_context_data(self, *args, **kwargs):
		context = super(FilterMixin, self).get_context_data(*args, **kwargs)
		qs = self.get_queryset()
		ordering = self.request.GET.get(self.search_ordering_param)
		if ordering:
			qs = qs.order_by(ordering)
		filter_class = self.filter_class
		if filter_class:
			f = filter_class(self.request.GET, queryset=qs)
			context["object_list"] = f
		return context

class UserProductHistoryListView(LoginRequiredMixin,ListView):
	
	#template_name = "products/product_list.html"
	template_name = "products/user-history.html"

	def get_context_data(self,*args,**kwargs):
		context = super(UserProductHistoryListView,self).get_context_data(*args,**kwargs)

		cart_obj=Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context

	def get_queryset(self,*args,**kwargs):
		request = self.request
		views   = request.user.objectviewed_set.by_model(Product, model_queryset=False) 
		#viewed_ids	=[ x.object_id for x in views]
		return views


class ProductListView(ListView):
	#queryset = Product.objects.all()
	template_name = "products/product_list.html"

	def get_context_data(self,*args,**kwargs):
		context = super(ProductListView,self).get_context_data(*args,**kwargs)

		cart_obj=Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context

	def get_queryset(self,*args,**kwargs):
		request = self.request
		return Product.objects.all()


class ProductDetailSlugView(ObjectViewedMixin, DetailView):
    queryset = Product.objects.all()
    template_name = "products/product_detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        instance = self.get_object()
        context['cart'] = cart_obj
        context["related"] = sorted(Product.objects.get_related(instance)[:6], key= lambda x: random.random())
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Uhhmmm ")
        return instance




class ProductDetailView(DetailView):
	model = Product
	#template_name = "product.html"
	#template_name = "<appname>/<modelname>_detail.html"
	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
		instance = self.get_object()
		#order_by("-title")
		context["related"] = sorted(Product.objects.get_related(instance)[:6], key= lambda x: random.random())
		return context


def product_detail_view(request,pk=None,*args,**kwargs):
	print(args)
	print(kwargs)
	
	#instance = get_object_or_404(Product,pk=pk)
	#try:
	#instance = Product.objects.get(id=pk)
	#except Product.DoesNotExist:
	#	print('no product here')
	#	raise Http404("Product doesn't exist")
	#except:
	#	print("huhhh?")
	#context = {
	#	'object' : instance
	#}
	#print(context)
	instance = Product.objects.get_by_id(pk)
	if instance is None:
		raise Http404("Product doesn't exist")
	context = {
		'object' : instance
	}

	return render(request,"products/product_detail.html",context)

src/products/templates/products/snippets/card.html
{% load staticfiles %}
  <div class="card-deck">
    <div class="card" style="width: 20rem;">
        {% if instance.get_image_url %}
          <a href="{{ instance.get_absolute_url }}"><img class="img-fluid" src="{{ instance.get_image_url }}" alt="{{ instance.title}} logo"></a>
        {% endif %}
      <div class="card-body">
          <h4 class="card-title">{{ instance.title }}</h4>
          <p class="card-text">{{ instance.description|linebreaks|truncatewords:14 }}</p>
          <p class="card-text">₹{{ instance.price }}</p>
          
          <div class='text-center'>
              <a href="{{ instance.get_absolute_url }}" class="btn btn-primary my-2">View</a>
              {% include 'products/snippets/update_cart.html' with product=instance cart=cart %}
          </div>
      </div>
    </div>
  </div>



{% block container %}
  <div class='container-fluid mt-5'>
    
    <div class="card-deck">
      <div class="owl-carousel owl-theme">
        {% for product in products2 %}
          <div class="item">
            <div class="card cardColor">
              <div class="card-body">
                {% if product.get_image_url %}
                  <a href="{{ product.get_absolute_url }}"><img class="img-fluid" src="{{ product.get_image_url }}" alt="{{ product.title}} logo"></a><hr/>
                {% endif %}
              
                <h3 class="card-title mt-2">{{ product.title }}</h3><hr/>
                <p class="card-text1 descriptionColor">{{ product.description|truncatewords:14 }}</p>
                <p class="card-text">₹{{ product.price }}</p>
              
                <div class='text-center'>
                  <a href="{{ product.get_absolute_url }}" class="btn btn-primary my-2 float- center">View</a>
                      {% include 'products/snippets/update_cart.html' with product=product cart=cart %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div><hr/>
{% endblock %}


 

src/products/templates/products/snippets/card1.html
{% load staticfiles %}
<div class="card-deck">
  <div class="card">
        {% if instance.get_image_url %}
          <a href="{{ instance.get_absolute_url }}"><img class="img-fluid" src="{{ instance.get_image_url }}" alt="{{ instance.title}} logo"></a>
        {% endif %}
      <div class="card-body">
          <h4 class="card-title">{{ instance.title }}</h4>
          <p class="card-text">{{ instance.description|linebreaks|truncatewords:14 }}</p>
          <p class="card-text">₹{{ instance.price }}</p>
          
          <div class='text-center'>
              <a href="{{ instance.get_absolute_url }}" class="btn btn-primary my-2">View</a>
              {% include 'products/snippets/update_cart.html' with product=instance cart=cart %}
          </div>
      </div>
    </div>
</div>







 

src/products/templates/products/snippets/featured_card.html
{% load staticfiles %}
		
<img src="{% static 'images/img14.jpg' %}">
	<div class="container mt-3">
		<div class="row">
				<div class="owl-carousel owl-theme">
					{% for instanse in object_list %}
	        		<div class="item">
		      			<div class="card">
		        				{% if instance.get_image_url %}
		          					<a href="{{ instance.get_absolute_url }}"><img class="card-img-top" src="{{ instance.get_image_url }}" alt="{{ instance.title}} logo"></a>
		        				{% endif %}
		        			<div class="card-body">
						        <h4 class="card-title">{{ instance.title }}</h4>
						        <p class="card-text">{{ instance.description|linebreaks|truncatewords:14 }}</p>
						        <p class="card-text">₹{{ instance.price }}</p>
		        			</div>
		        			<div class='text-center'>
		        				<a href="{{ instance.get_absolute_url }}" class="btn btn-primary my-2">View</a>
		        				{% include 'products/snippets/update_cart.html' with product=instance cart=cart %}
		    				</div>
	    				</div>
					</div>
	    			{% endfor %}
				</div>
		</div>
	</div>

src/products/templates/products/snippets/update_cart.html
{% load staticfiles %}

<form class='form-product-ajax' method='POST' action = '{% url "cart:update" %}' data-endpoint='{% url "cart:update" %}' class="form">{% csrf_token %}
<input type='hidden' name='product_id' value='{{ product.id }}'/>
	
	<span class='submit-span'>
	{% if product in cart.products.all %}
		In cart <i class="fas fa-cart-plus">In cart </i><button type='submit' class="btn btn-link">Remove?</button>
	{% else %}
		<button type='submit' class="btn btn-success">Add to Cart</button>
	{% endif %}
	</span>
</form>